name: Android APK Build (Mobile Fix)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Update LSPatch
        run: ./gradlew setupLSPatch

      - name: Build APK (Debug)
        run: ./gradlew assembleDebug

      - name: Find APK
        id: find_apk
        run: |
          DEBUG_APK=$(find app/build/outputs/apk/debug/ -name "*.apk")
          echo "DEBUG_APK=$DEBUG_APK" >> $GITHUB_ENV

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GrindrPlus-Zeletris-Build
          path: ${{ env.DEBUG_APK }}
